<?php
//ini_set('display_errors', 1); ini_set('display_startup_errors', 1); error_reporting(E_ALL);
	require("includes/form_constants_both.php");
	require "dbcon_open.php";
	require "class.phpmailer.php";
	
	exit;

	
	$emails = array('nikhil.yadav@intel.com','shri.hiremath@gmail.com','shaduec@gmail.com','settappa.malleswarappa@gmail.com','carel@cohred.org','mjosmi@gmail.com','romenbanerjee@gmail.com','jvrao1994@gmail.com','prasanta.saha@3ds.com','v.mahadesha@stpi.in','sumogh76.gec@gmail.com','sujith.nambiar@mt.com','parikshithkustagi@gmail.com','pbgouda72@gmail.com','gaurav.luthra@globalfoundries.com','malavika.babu@walmartlabs.com','r.s.sudarsan@gmail.com','n.siddappa@stpi.in','sanjeevkeskar@yahoo.com','shubha.k@ittiam.com','hamshine@gmail.com','ravirao@qti.qualcomm.com','patil.archanad1@gmail.com','puneeth@karmic.co.in','dvvardhaman@gmail.com','suni.jntu@gmail.com','vinay@v5semiconductors.com','deepaknandini82@gmail.com','arun@kanooelite.com','swarup.maji@stpi.in','mujeebsaber@gmail.com','dsram49@gmail.com','gmegavannan@gmail.com','bhanuprasad1985@hotmail.com','ramaprasad.g@samsung.com','shaju.sukumaran@accenture.com','ashokk@vmware.com','simachal.samantaray@fnf.com','sandeep_nagbhushan@infosys.com','swaroop@brigadereap.com','rajendra.velagapudi@cyient.com','murthy.munipalli@incapcms.com','sandeep.kumar@stpi.in','sandee.rai@stpi.in','veerabhadra@stpi.in','ssundramurthy@nasscom.in','k.suryakanth@stpi.in','senthilp26@gmail.com','agmprcsb.lhoban@sbi.co.in','csrao@quadgenwireless.com');

	$emails = array('naveenanroopan@gmail.com','sswaminatha9@dxc.com','captbssaluja@gmail.com','sureshpurohitt@gmail.com','choudharysunita0202@gmail.com','arindam.raymondal@stpi.in','sneha.g.rai@gmail.com','npujari@vmware.com','vimal.mahendru@indoasian.com','mujeeb.m.abdul@jpmorgan.com','mskishore.online@gmail.com','nyamannavar@gmail.com','n1234rao@gmail.com','deepakbabu.tr@zf.com','tarannum.n@gmail.com','k.sunil@analog.com','rbpawar2@gmail.com','somageethashekar@gmail.com','rchakraborty@psi.de','deirdre.kent@international.gc.ca','badaplavar@gmail.com','umeshy.cj@gmail.com','maheshgecr@gmail.com','itsupport@aerocoe.in','lokeshtgec@gmail.com','mikael.eriksson@sscspace.com','madanb@karmic.co.in','anantha.bhat@cerium-systems.com','yamuna.doddanna2003@gmail.com','vinodhkumar_allalli@dell.com','lokesh.cr@dell.com','itbtsec@gmail.com','itcell.dpibhopal@gmail.com','laxmi_rag@yahoo.com','madhurya23@gmail.com','divyaraj@iiitb.ac.in','vivek.bhatia@thyssenkrupp.com','hudha.n96@gmail.com','safina@sanzedu.com','sekermail10@gmail.com','snpgwpt@gmail.com','suhas@globalsinc.com','shwetadua3009@gmail.com','vksjadhav.jadhav@gmail.com','vidyavathi@bitm.edu.in','nitin.rai@stpi.in','skannur022@gmail.com','kbprakash04@gmail.com','william.l.blair@lmco.com','anandappa2008@gmail.com');
	
	$emails = array('dinkar.bhat@manipal.net','leelavathv22@gmail.com','rakesh.singh@stpi.in','somashekar.kp@gmail.com','ashoka.puttegowda@se.com','amit.arora@stpi.in','shilpa.sudhir@gmail.com','sathishk@vagroup.com','sjpanand@gmail.com','mmyuktha@gmail.com','mshegedar@gmail.com','prakashs@karmic.co.in','wallurevijay@gmail.com','jilani.hmm@gmail.com','roopa.nagaraju@freudenberg.in','nagarajhanchinmani@gmail.com','draraskumar@gmail.com','kmk.gpt@gmail.com','raymond.jhts@gmail.com','fazaluddeen.dm@gmail.com','poori14apr@gmail.com','mamathagopal511@gmail.com','raju.jadar@gmail.com','nagarajm459@gmail.com','raghavendra.crclk@gmail.com','kishnrgdg@gmail.com','dr.suresh@bitm.edu.in','chandkala.2009@gmail.com','ravindra@vollmer-group.com','bidar.nemmadi@gmail.com','karthik.j30@gmail.com','spshanupatil@gmail.com','gknisarga@gmail.com','satish@yournest.in','shobha.shivu1@gmail.com','vinu.gsvinutha@gmail.com','seenappakv@gmail.com','sumahrvivanm@gmail.com','mhsharavathi06@gmail.com','srivathsan.p@gs.com','bhagyavana@gmail.com','sneha.singh@mmactiv.com','Sprb4@allstate.com','gnsprasanna@iiitb.ac.in','achfj@allstate.com','janhavi.yadwad@gmail.com','utsav@pdatradefairs.com','gr.jayaprada@gmail.com','slv.vls@gmail.com','srchougula@gmail.com');

	$emails = array('savithaharsha89@gmail.com','ajmal76@gmail.com','pallavipatil2382@gmail.com','it@dalvkot.com','mailsubho@yahoo.co.uk','n.vijayaraj@stpi.in','naganna.sollapure@gmail.com','1983jayashree@gmail.com','bhosle.123@gmail.com','slkn1999@gmail.com','thirasaku@gmail.com','naibhariprasad@hotmail.com','deepak10.b@tcs.com','dinesh@wehrhahn.de','pplgect@gmail.com','prasadns1710@gmail.com','ekant.tyagi@in.ey.com','nidhi.sharma@stpi.in','sunil.sagane@thyssenkrupp.com','divya.raghavachar@in.ey.com','pkdas@stpi.in','gopalkrishnahl@gmail.com','madhud.gec@gmail.com','praveensindagi@gmail.com','l.narayana.stpi@gmail.com','debajit.sarma@stpi.in','ushassree@gmail.com','kantharaju.hm@gmail.com','roopa.gec@gmail.com','satyanarayan.das01@sap.com','sumit.karkamkar@thyssenkrupp.com','raghu8755@gmail.com','amiya.mohanty@secotools.com','nitinbhandari119@gmail.com','nbhat2k18@gmail.com','harsha@studioilluzion.com','raghavshet78@gmail.com','banuflgpt25@gmail.com','tvprabs@iisc.ac.in','aumsaru@gmail.com','prashanth_ks@intuit.com','Anshuman_Kumar@intuit.com','aliza_carpio@intuit.com','sanket@intuit.com','sunitha.v6@gmail.com','usshenoy1004@gmail.com','kvenkatesha.k@gmail.com','soamiddas@eaton.com','prashanthmgowda3755@gmail.com','rajareddyh1966@gmail.com');


	$emails = array('uttam215@gmail.com','reshmaattavar@gmail.com','manjunath.jade@gmail.com','supriya.upadhya@manipal.net','schroeder1956@gmail.com','tk.srikanth@iiitb.ac.in','neel.m.dy@gmail.com','mahesh.magadum@gmail.com','veeresh.rabinal@gmail.com','omyreddy@gmail.com','shivamanjana4900@gmail.com','stshedole@gmail.com','anandraj.anthony@ringfeder.com','gfgcpeenya@gmail.com','neetha.melanta@tcs.com','sdasgupta@moog.com','prakash.ranjan@stpi.in','subrat.nayak@stpi.in','lathavprabhu@yahoo.com','sowmya.mtech@gmail.com','shamkr@pentawis.com','venkyp25@gmail.com','tsrvindra@gmail.com','manish.y.gupta@gs.com','rudresh.sgl@gmail.com','v.sharma@stpi.in','sangappaganiger1973@gmail.com','rsgavai@gmail.com','rahul.singh@stpi.in','sujatha4.b@tcs.com','vvrampur@gmail.com','snch2025@yahoo.in','amrutapranesh@gmail.com','arshad_bvb@rediffmail.com','shiva779218@gmail.com','psandeep.gpt@gmail.com','ram.pratap@stpi.in','pmpatil22@rediffmail.com','prakashanabur@gmail.com','rmuddebihal@gmail.com','bsiddeshi@gmail.com','raj.enggs@gmail.com','faruq.mdy@gmail.com','bs.saluja@lntinfotech.com','veeresh1971@gmail.com','sureshmg.gpt@gmail.com','mshankar747@gmail.com','plgirish45@gmail.com','tg.braju@gmail.com','lakshminarayana70@gmail.com');

	$emails = array('ss.sharath@gmail.com','ramuramuj1964@gmail.com','jitendra.kulkarni@stpi.in','anitharam72@gmail.com','ipildbpur@gmail.com','th.naveen@gmail.com','shashi.mongia@stpi.in','vathsala.dte@gmail.com','bhagya109@gmail.com','ravi.thaker@stpi.in','chatterjees@state.gov','anilesh@zensciences.com','rmanjunatha1962@gmail.com','manjit.bali@lntinfotech.com','annu1967@gmail.com','samy@maxvytech.com','pdtalawar23@gmail.com','ritvik.vipra@gmail.com','prasenjit.ghosh@stpi.in','vinayakkjadhav.cs@gmail.com','nyoga1993@gmail.com','ptamraparnee@gmail.com','chandan_om@yahoo.co.uk','vsanantpur@gmail.com','rnandeesha@gmail.com','akarsh.shetty@lntinfotech.com','raju.shobha93@yahoo.com','sdrachaiah@gmail.com','satyam.singh@stpi.in','deepak.x.ramu@jpmorgan.com','atul.singh@stpi.in','jomon.alex@stpi.in','nishikantjoshi@yahoo.com','drlavanyahegde@gmail.com','roopanjalifeedback@gmail.com','incharashivkumar16@gmail.com','achyut.savanur@techmahindra.com','ranjana.singh@stpi.in','santhosh.p@ionidea.com','ashok.kumar@lntinfotech.com','janadri.c.s@gmail.com','jsspdaec@gmail.com','kavya.ac@gnail.com','rajshree.shinde@stpi.in','jambu6995@gmail.com','sathishsb@gmail.com','bdt.arun@gmail.com','vamshish1994@gmail.com','biswajit.mishra@stpi.in','deepanshu.kansal@stpi.in');

	$emails = array('chandrikagv@yahoo.com','nandalike_bhat@yahoo.co.in','sbmallur@gmail.com','srinischay03@gmail.com','brp5679@gmail.com','rachanavamshish94@gmail.com','prashanth.h@manipal.net','deepikadear@gmail.com','gouda321@gmail.com','shatajpn@gmail.com','principalaiet08@gmail.com','shivamkumar.dubey@stpi.in','srikantgk09@gmail.com','servermoody@gmail.com','anandsadhu205@gmail.com','vinayhb083@gmail.com','principalgeckarwar@gmail.com','padmasatyamanianu@gmail.com','aditi6147@gmail.com','murali.krishna@stpi.in','tomansen907@gmail.com','kchannaveeragouda@rymec.in','shivananda@manipal.net','raveendrakit@gmail.com','raghavendrarx135@gmail.com','veenabpatil@rediffmail.com','uraju54@gmail.com','bngopalakrishna@gmail.com','sudarshansv@gmail.com','nemi.chand@stpi.in','shiv.syscongroup@gmail.com','ho.natmo@nic.in','saji.krishnan@gov.in','tushar.tanay@hp.com','sonialamba94@gmail.com','ramya.coffeeboard@gmail.com','manish.gupta@growxventures.com','bhushana.hm@gmail.com','sathish.env@gmail.com','prashanthnaik033@gmail.com','sushmathenkanidiyoor@gmail.com','nataraj.kuntoji@gmail.com','gptsorab1996@gmail.com','simulia@aercoe.in','ums2020@gmail.com','mallikarjuna.hm@gmail.com','bhuri.singh@stpi.in','pushpa1984mys@gmail.com','siddiquebeary@bearysgroup.com','muraligeck@gmail.com');
	
	$emails = array('sgdevika@gmail.com','kptmng@gmail.com','suma.kale@mindtree.com','digambar.trimuke@gmail.com','cm_patil@yahoo.co.in','hsp1070@gmail.com','mallikarjunaa@bitm.edu.in','elango1.india@gmail.com','mshanmugam168@gmail.com','bmrudreshan@mail.com','jyotirmoy.sengupta@stpi.in','anilkumar.hembram@stpi.in','ananthrathod@gmail.com','hnkota@yahoo.com','gfgc.shikaripura1980ku@gmail.com','m.shankarappa@gmail.com','shikhapathak16@gmail.com','prashanth333.ece@gmail.com','vishal.sharma@stpi.in','devu.infy11@gmail.com','polestarputta@gmail.com','lokeshnallur4@gmail.com','kamblepurnima529@gmail.com','leenamaria668@gmail.com','s.srithar@stpi.in','visubvb35@gmail.com','nagarajbpatil@gmail.com','prathi.chikkaiah@gmail.com','anchal.pandey@stpi.in','mgirijapatil@gmail.com','nalini.pandey@stpi.in','yogesha@gms-india.com','lakshmipaloti1979@gmail.com','hklakshmana@gmail.com','neelarohini@gmail.com','kalasadylp@gmail.com','lalit.singh@stpi.in','jayalakshmi.d@stpi.in','sandeep.nair@stpi.in','rajendradhane@gmail.com','mahesh.116@rediffmail.com','siddhartha.shekhar@stpi.in','sumangalamaradi@gmail.com','mbratnapurkar@gmail.com','171gpthubli@gmail.com','dadafeer.gaunse@stpi.in','drkgchandrashekar@gmail.com','nisargamodini@gmail.com','jyothimvr@gmail.com','shyleshchandra444@gmail.com');

	$emails = array('appaiahb@vmware.com','praneet.paliwal@stpi.in','vijayamlr33@gmail.com','siddartha.bhatt@wdc.com','sunit.pillai@stpi.com','sadathnoori@gmail.com','principaldvspt346@gmail.c','yamunaraju2003@gmail.com','keerthin.90@gmail.com','mukthambika.sm@gmail.com','drbcs2007@gmail.com','rturashmi@gmail.com','mamathasairam@gmail.com','sitaram.banda@gmail.com','nkaribasappa@gmail.com','vbgfgc@gmail.com','bpbaikar@gmail.com','dr.nsagadi@gmail.com','ravi.varma@stpi.in','gptchnagar@gmail.com','kip.gec@gmail.com','afshank5798@gmail.com','bapubindhu@gmail.com','jaga20dec@gmail.com','gptdevadurga.184@gmail.com','pradeep.kumar@manipal.net','balabheem.21@gmail.com','rashmichannaiah70@gmail.com','rudhram@bionicyantra.com','principaldvspt346@gmail.com','girish.smp66@gmail.com','praful.patinge@stpi.in','sundar.singh@stpi.in','sachin.narule@stpi.in','nr.jayachandra@gmail.com','sharathknaik@gmail.com','n.prajwal@stpi.in','debsankar.dutta@stpi.in','jeeva402@gmail.com','tusharnandimath@gmail.com','ameya.shirodkar@stpi.in','deepapradeeptvm@gmail.com','praveenkumarputtappa@gmail.com','priyankapatil0405@gmail.com','k.valikar@stpi.in','maggpt@rediff.com','ycbasaappa63@gmail.com','machander33@gmail.com','kcrshankar@gmail.com','pramani@vmware.com');

	$emails = array('bgsrnd@sjcit.ac.in','ritesh.goel@stpi.in','vnagaraj.v@stpi.in','prakyathiraj@gmail.com','sanjay.tyagi@stpi.in','kirakumar.b@stpi.in','nts.shashi@gmail.com','reginalsuganthi@mccblr.edu.in','pinnamaths@gmail.com','rathna.naganna@gmail.com','sony.anmol@gmail.com','umanarendra.yeligar@gmail.com','vinitha.kumari@stpi.in','director182016@gmail.com','pksjp2013@gmail.com','sr.nevin@stpi.in','g.megavannan@stpi.in','kanchinb18@gmail.com','bhuvikirthi0810@gmail.com','p.senthilkumar@stpi.in','jitendra.rathor@stpi.in','shanmukh.p@stpi.in','prleswari@cdac.in','magesh@cdac.in','raghu.me01@gmail.com','randhir.k@stpi.in','ranga.hassan@gmail.com','skcgpt@yahoo.com','kgchandrashekar@yahoo.com','scott.mcleod@international.gc.ca','archana.jagan8@gmail.com','sunny.sehgal@stpi.in','somu.maranoor@gmail.com','eswarappa123hc@gmail.com','kb.sasi@stpi.in','ravi.sidlipur@gmail.com','babygowda@gmail.com','principalkrpet@gmail.com','gpth182@gmail.com','krishnappa.anu@gmail.com','dikson.christian@stpi.in','yogeshwar.ade@stpi.in','raks3586@gmail.com','virupaksha.g@samsung.com','p.jithesh@stpi.in','gpt.mohan@gmail.com','yndambu123@gmail.com','ashwini.frnds@gmail.com','gfgcsargur@gmail.com','ks.nchandra@gmail.com');

	$emails = array('vkirankumar87@gmail.com','asha.krishnan@stpi.in','manjit.nayak@stpi.in','hitesh.narkhede@stpi.in','priyankamktg2@gmail.com','amandeep.kaur@stpi.in','pushpahr15@gmail.com','dcm@bangalore.mfa.gov.il','prashanth074@gmail.com','amol.lakras@stpi.in','parisra91@gmail.com','rangarajusksjti@gmail.com','r.shabna@stpi.in','vijaykumark47805@gmail.com','srikrishna.maity@stpi.in','pbm.gpt@gmail.com','nr.jayachandra@stpi.in','gpt146@gmail.com','aditya61097@gmail.com','chinmaya@stpi.in','pralladareddyonimani@gmail.com','shivling74@hotmail.com','mpmallesh2011@gmail.com','lokeshn.85@gmail.com','devarajlaxman@gmail.com','z.b@taffconsulting.com','sundar@taffconsulting.com','poornimaparameshwar28@gmail.com','thomasgunaseelan@gmail.com','sreeja.devi@stpi.in','srbiradar@gmail.com','m.purushotham@stpi.in','neeraj.alekar@stpi.in','h.afreen@stpi.in','mh.azharuddin@stpi.in','devesh@stpi.in','tsmahesh1800@gmail.com','satyagupta09@gmail.com','reema.raj@stpi.in','s.reji@stpi.in','prasadrao@stpi.in','vikas.g@stpi.in','018ajaykumar@gmail.com','k.prakash@stpi.in','rencita.dsouza@manipal.net','somasekarj@gmail.com','somas@mysmindia.com','raghavendra.solanki@stpi.in','chandravarma.kv@stpi.in','suma.patil@stpi.in');

	$emails = array('madhu@stpi.in','jinubala.v@stpi.in','suresh.hosamani@stpi.in','vijay.b@stpi.in','pvatsa@hotmail.com','agnetha.rodrigues@manipal.net','hr.sunil@stpi.in','sirisha.a@stpi.in','premmsingh1973@gmail.com','ygreddy@stpi.in','anju.kairali.chandran@intel.com','aswin.adityan@3ds.com','ravi@startupxseed.in','prathima.suvarna@manipal.net','navigation@aerocoe.in','jsomasekar@gmail.com','mm.pramodsa@stpi.in','b.mohana@stpi.in','sunil@mite.ac.in','rameshrmz@yahoo.com','karthik.kumar@manipal.net','saraswatikutir@gmail.com','hs.kantharaju@stpi.in','sujitkc@iiitb.ac.in','vinuta.hiremath@gmail.com','rasika.kabade@stpi.in','neerajv@xilinx.com','tasmiyapatel1943@gmail.com','sadiq_ise@rediffmail.com','narayan.tosur@praxien.com','ganesh.b@gevasol.com','sushanth.shetty@stpi.in','arumugam.pitchai@iiap.res.in','chrisphin.karthick@iiap.res.in','sanjay.gupta@stpi.in','rameez.raza@manipal.net','dpa6@3ds.com','jitendra.kumar@stpi.in','1018usha@gmail.com','anjaneyulu.chilakapati@3ds.com','n.lokesh@stpi.in','sanjay.naik@in.ibm.com','ub.vidya@stpi.in','bs.bhavana@stpi.in','jdinesh@iiitb.ac.in','aqsamishrikoti@gmail.com','aruj.bhuyan@stpi.in','rsravikrishna@gmail.com','b.umesh@stpi.in','suresh.kumar@stpi.in');

	$emails = array('varun@mite.ac.in','ch.cyseck@karnataka.gov.in','m.jaikar@stpi.in','arya.r@sasyaka.com','ssrk63@gmail.com','m.ganesh@stpi.in','d.indumathi@stpi.in','m.ganesh@stp.in','anand.kumar@stpi.in','b.thangaraju@iiitb.ac.in','sk.babitha@stpi.in','kchannaveeragouda@rymec.on','krishna@nasscom.in','keithf@sjec.ac.in','amitkumar.rai@stpi.in','aishwaryaswamy333@gmail.com','shashankaghatage@gmail.com','madhu.s@ornnova.com','g.jayanthi@stpi.in','kunal.p@sasyaka.com','v.ramasubramanian@iiitb.ac.in','as.ajay@stpi.in','shashankaghatage@yahoo.com','pavithra.nayak@manipal.net','srinivas.an@pisquaretech.com','narang.anish93@gmail.com','deepa.b@stpi.in','c.mannar@3ess.in','mpdvizag@gmail.com','csrao@quadgen.com','rameshy@stpi.in','adarshk@mite.ac.in','sslc91.2@gmail.com','krishnaraj.bhat@manipal.net','naveens.ec18@sahyadri.edu.in','ahasselvaraja@gmail.com','rajas@synopsys.com','kritika@nasscom.in','basu@criyagen.com','amitav@timetooth.com','greetsathya@gmail.com','masudhakaran@gmail.com','prashanthkumar.m@in.bosch.com','iamsridharkrishna@gmail.com','harsha.holla@manipal.net','maneeth.pd@gmail.com','akshataaa98@gmail.com','rapolusushma@gmail.com','verghese.mu@mgtechsoft.com','principal@git.edu');

	$emails = array('rajkambl@cisco.com','tousif@migitinstruments.com','rameshreddyvtu@gmail.com','raakesh.menon@vodafoneidea.com','chakradhar.rao@quest-global.com','pankajsharma.mail92@gmail.com','maanikgroup@yahoo.com','niranme76@gmail.com','prakash.cavale@gmail.com','prv.dwivedi@gmail.com','amit.bansal@stpi.in','feroz.parray@stpi.in','ibrez@survivatechnologies.com','mukil@survivatechnologies.com','arjun@survivatechnologies.com','shafeek.asharaf@minionlabs.tech','ganesh.nayak@stpi.in','jagannathan.t@gmail.com','vivek@hexagon.com','sanjay.desai@minionlabs.tech','kishoredk@minionlabs.tech','bhaskuma@cisco.com','gokul@minionlabs.tech','rajengoe@cisco.com','nitin.bakshi@se.com','kumar@drivebuddyai.com','manjunath.kulkarni@manipal.net','rishi.dixit@pwc.com','shkalita@cisco.com','rooparaji2004@gmail.com','sri.harikumar10@gmail.com','khanmj99@gmail.com','manas.das@intel.com','niljoshi27@gmail.com','rathnadhar@gmail.com','satish.venkatachaliah@hm.com','deepak.balram@gmail.com','itika.singhal@gmail.com','swadhospitality@gmail.com','alexmurur@gmail.com','jkumar@kitven.com','mk.kruthavarma@stpi.in','ajmal.fawad@vdmaindia.org','msjaggal@gmail.com','birenghose@gmail.com','mdpmubmgf@birac.nic.in','santiago.mendez@quest-global.com','mbopanna@gmail.com','coo@ableindia.org.in','sunitamallikarjuna@gmail.com');

	$emails = array('prashanth.bhat@manipal.net','vivek.rc@nie.ac.in','pushpanandu22@gmail.com','pushpavtu@gmail.com','neeraj.patil@healthheal.in','deena.dayalank@kcc.com','yadhucse@gmail.com','siddaiah.ns@stpi.in','daya.airody@ashakiranagroup.com','puraikar22@gmail.com','ranjan.rao@manipal.net','neo.deepu@gmail.com','ahmedparvez@yahoo.com','srinivasa.murthy@tcs.com','shiva@bionicyantra.com','raghukumar1976@gmail.com','yathishchandra18@gmail.com','rohini@essc-india.org','narasim@manipal.net','ravinder.sharma@trillion-bits.com','narayananr@vmware.com','shashisv7@gmail.com','naveen.agrawal@intel.com','rananapriya8@gmail.com','milind.naik@avnet.com','mohankumar19@hotmail.com','vkparvati@gmail.com','salagar.raju@gmail.com','manoj.pantangi@optimizedsol.com','toamaaira@gmail.com','marusidh@gmail.com','raghunath.ramaiah@mindtree.com','snehanshu@nasscom.in','sndhrgowda21@gmail.com','vilius.cepulis@teltonika.lt','vb@nrdcs.lt','navratan@mail.nasscom.in','dklepone@enterpriselithuania.com','jogender.singh@stpi.in','paulius@passcamp.com','e.stasiene@bankera.com','povilas@ondato.com','dia@sahyadri.edu.in','lukas@turingcollege.com','dinesh.bhat@itcinfotech.com','lina.kutkauskaite@urm.lt','dayanand.patel@wipro.com','sanjay.jain@camsonline.com','rajesh@inflowtechnologies.com','viral.gala@teleperformance.com');

	$emails = array('sudhakar.tiwari@dmartindia.com','jkireilis@enterpriselithuania.com','k.guruprasad@stpi.in','agne.sakalauskaite@urm.lt','vinit.teredesai@mindtree.com','s.nagamani@stpi.in','alok.nayak@stpi.in','parasgathani5@gmail.com','rmanickam@vmware.com','s.rajalakshmi@stpi.in','ks.sushma@stpi.in','krsmurthy09@gmail.com','bala@uniqueperform.com','rachanavamshish19@gmail.com','pijush.debnath@stpi.in','b.deepanshi@stpi.in','vivek.sharma@st.com','ishu.agrawal@stpi.in','jvgoraba@gmailcom','niranjan.pol@seagate.com','op.mathur@stpi.in','bsnandakumar@gmail.com','ashwini_aggarwal@amat.com','saswati.ray@mouser.com','dipak.kumar@stpi.in','s.rohith@stpi.in','t.sudhakar@stpi.in','p.jimnesh@stpi.in','jr.joshi@stpi.in','swetha.kolvekar@stpi.in','k.anand@stpi.in','nikhil.narasimha@vigyanlabs.com','vatsa@vigyanlabs.com','m.bibhu@stpi.in','kailash.babu@stpi.in','neville.kavarana@wpa.org.uk','sachin@stpi.in','rajib.das@stpi.in','ravi.t@stpi.in','rajesh@est-cap.com','sarala.parthasaradhy@stpi.in','jayesh_k@trigent.com','ankesh.kumar@stpi.in','subodh@stpi.in','smagi@commvault.com','nkraghunandan@yahoo.com','usha@sahafund.con','k.renuka@stpi.in','schandore@gmail.com','gc.mallesha@stpi.in');

	$emails = array('sanjay.rao@sc.com','pratheekshakldl@gmail.com','jeevan.balasubramanian@meritor.com','sv.shaluraj@stpi.in','sanjaykumar.verma@stpi.in','shubham.sharma@stpi.in','cn.komala@stpi.in','aneesh.kumar@stpi.in','vinayak.salve@stpi.in','ravindra.aroor@stpi.in','shashikant.patel@stpi.in','ramakrishna.g@stpi.in','manojkumar.singh@stpi.in','jayaprakash@stpi.in','sg.rajan@stpi.in','rajkumar.verma@stpi.in','v.sasikumar@stpi.in','deepakkumar.chaudhry@stpi.in','ravikiran.a@numocity.com','srini@vigyanlabs.com','clab@coffeelabindia.com','ranbir.mansingh@gmail.com','hemlata.azad@stpi.in','ravi.b@stpi.in','girish.aradhya@customersquare.com','nandkishore.gupta@hsbc.co.in','jc@quaadbotics.com','vivek.khemka@harman.com','sred@sonata-software.com','pvrai@pixelsoftek.com','pkalbhavi@novigosolutions.com','vibahv@justrobotics.in','prabhuraj_1464@yahoo.com','chai.bhoomi.01@gmail.com','suresh.bv@ksrsac.in','sanjay.khanchandani@allstate.com','gururaj.bnk@gmail.com','fdait.kbits@gmail.com','ram@stpi.in','coo@juincubator.com','ayusha@amazon.com','ragmut25@in.ibm.com','vrinda.maskeri@intel.com','rohith09@gmail.com','leon.christian@technicolor.com','sandra.patrao@technicolor.com','nkv@hotmail.com','priya@multiversal.co.in','harishbendegeri@gmail.com','re@vtu.ac.in');

	$emails = array('mmprasad2001@gmail.com','manjunatha.maiya@philips.com','hardik.panchal@datamine.co.in','vishnusanjay@ictacademy.in','manoj@transitusnexgen.com','vinod.jayanna@transitusnexgen.com','manas.pandey@transitusnexgen.com','dev@transitusnexgen.com','mgrskill.ktech@gmail.com','veeresh_shetty@mentor.com','ganesh@purplerock.in','gurupadeshvh@gmail.com','sureshbabu@ictacademy.in','som@bharat.fund','venkatesh@premiersystems.co.in','vishnuprasad@ictacademy.in','registrar@iiitb.ac.in','joy@genrev.in','rahul.arya@altran.com','venkata.raghavan@escaladelegal.com','giri.raju@lnttechservices.com','ankit@bcshettyco.com','ashok.m@altencalsoftlabs.com','ramesh@magnatech-india.com','arvind_t@sangennovate.com','veerappan@tessolve.com','komalgurjar26@gmail.com','jitendra.chaddah@intel.com','shrikant@stpi.in','venkata.simhadri@moschip.com','sanjay.gupta@nxp.com','shrikant@stpi','suryaprakash.reddy@actcorp.in','arvind.kumar@genisys-group.com','PRATUL.TANDON@GMAIL.COM','PALLAVI.PARAB@HDFCBANK.COM','PRARTHANA.AGRAWAL@HDFCBANK.COM','KIRANDEEP.KOUR@HDFCBANK.COM','shiva.kumar@oneindia.co.in','skb@bhasin.in','anandhkumar.s@siemens.com','ronnie.vincent@i-exceed.com','sh_manjunath@rediffmail.com','pradeep.vajram@alphaics.com','binu@xpereos.in','rnagaraj@wipfli.com','pavan.r@embassyindia.com','bsumesh@prestigeconstructions.com','guru.ganesan@arm.com','bhushan.dhade@actcorp.in');

	$emails = array('prajot.helkar@stpi.in','sukanyabs71@gmail.com','nagesh.r@actcorp.in','bharathwadone@gmail.com','ujval.s@actcorp.in','jerrish.jacob@actcorp.in','anku.jain@mediatek.com','sannan.turabi@actcorp.in','narendra.varma@actcorp.in','anaini@xilinx.com','abhilash1.k@tcs.com','sunil.yajaman@actcorp.in','rajeev.naidu@actcorp.in','akhilesh.jj@actcorp.in','rkhushu@ti.com','srinivas.yakkundi@actcorp.in','ceo@krea.co.in','anshuman.b@actcorp.in','amit.kansal@actcorp.in','bhanue@prione.in','santosh.mugali@gmail.com','pa.itsds@gmail.com','pramodcb@gmail.com','kasettysiva@gmail.com','mili.chowdhary@technicolor.com','adci@iitr.ac.in','anand@nativepuppets.com','sanjeev.neelappa@yti.yokogawa.com','akhila.phadnis@intel.com','manjunatha_kukkuru@infosys.com','shivaitbt@gmail.com','heshashidhar@rediffmail.com','pandareesh@acu.ac.in','ravikumargk@bgsit.ac.in','ashok@acu.ac.in','bgsit@acu.edu.in','goudacivil@gmail.com','sridhar.h.n@intel.com','tourimkarnatakapublicity@gmail.com','md@kstdc.co','acs-tour@karnataka.gov.in','puja.malhotra@intel.com','vivekreddyvtu@gmail.com','murthy.s.k@intel.com','nd.triveni@stpi.in','a.samsonx.praveen.kumar@intel.com','bchandra72@gmail.com','vivek.sarkale@dsci.in','eshan.hira@dsci.in','aditya.bhatia@dsci.in');

	$emails = array('anand.raman@dsci.in','vinayak.nayak@manipal.net','nraj@manipal.net','kavyashreemk@sjce.ac.in','mathew@paqs.biz','abhishek@paqs.biz','vaidy@paqs.biz','avinashbn@gmail.com','prgheadskills.kits@gmail.com','shrinivas.bairi@intel.com','mohan@cache-tech.com','mgrmarketing.startupkar@gmail.com','techseckbits@gmail.com','exeassociate.kbits@gmail.com','vijetswadi@gmail.com','vaddin@rymec.in','srprog.itbt@gmail.com','shivaprasadoct@gmail.com','aeerbc@bwssb.gov.in','eeni@bwssb.gov.in','eic@bwssb.gov.in','eecmc3@bwssb.gov.in','acewwm2@bwssb.gov.in','kroopesha243@gmail.com','samuelpaulsuchan@gmail.com','amitarora1584@gmail.com','thanuja.mocapcoe@gmail.com','sujeeth.bodyscan@gmail.com','aravindmocapcoe@gmail.com','btsummit2020@syrow.in','shreeshadasa.17ec060@sode-edu.in','rashmirachh@gmail.com','ops.cyseck@karnataka.gov.in','kbitsoffice@gmail.com','mz.maaz@gmail.com','shivaramana.gouda@gmail.com','danu.noola@gmail.com','puneethhj2008@gmail.con','roshancse@gmail.com','faisal@techarc.net','bkitbhalki@gmail.com','principal@bldeacet.ac.in','nchikkanna1967@gmail.com','rajesh@embedsense.com','loganathanr.cs@hkbk.edu.in','fdppi@fdppi.in','naavi1@gmail.com','vijayacnkumar@gmail.com','diptesh.patil@hp.com','rajesh.chandra@hp.com');

	$emails = array('meghanak@vtu.ac.in','noorbanu.17cs048@sode-edu.in','pushala.s@gmail.com','zane@aspiremediaindia.com','harshita@aspiremediaindia.com','dojo@aspiremediaindia.com','bangalore@indo-german.com','praveensr42@gmail.com','pm.cyseck@karnataka.gov.in','prajesh.ar7@gmail.com','contact@artibraino.com','srbbims@yahoo.com','president@fkcci.in','principal@sjcit.ac.in','principal@rrce.org','hulsoor.shiv06@gmail.com','glenson@mite.ac.in','delmia@aerocoe.in','vikas.smg@gmail.com','vtushiva@gmail.com','anildevangavi_s@yahoo.co.in','pattanshettysanjay@gmail.com','dhanpati.sahu@jgdtec.com','naveen@tiebangalore.org','lakshmi.p@tiebangalore.org','tulika@tiebangalore.org','pratap.solapur@gmail.com','dr.mawaheed@gmail.com','manjunath@smartsustain.in','swaroopas04@gmail.com','rajshekhar7007@gmail.com','principalbit4@gmail.com','krishlakki92@gmail.com','bvgadgay@gmail.com','tc.thanuja@gmail.com','s.uplaonkar@gmail.com','principalmycem@gmail.com','shailakheni@gmail.com','drshubhangipatil1972@gmail.com','sreeramareddy90@gmail.com','suriakls@gmail.com','deeptishetty@vtu.ac.in','kshyam@moog.com','sarvesh.verma@intel.com','naveen.godishala@gmail.com','gopi.j@intel.com','manju.gn@intel.com','vivek.rs@intel.com','uttpal.dilipkumar.desai@intel.com','gayathri.h.l@intel.com');

	$emails = array('murthykrishnakn@gmail.com','manu.bharadwaj@siliconroad.vc','k.rajesh@samsung.com','visan.sdmcs@gmail.com','anil@slntech.com','drbinoymathew@gmail.com','coolyo4you@gmail.com','maheshshastri43@gmail.com','vinay.jha@mmactiv.com','aditya@chkdin.com','drindumathits@gmail.com','nagarajijari20@gmail.com','deepu3062@gmail.com','raga.sarika@gmail.com','sowjanya_mn@vtu.ac.in','kgshivam@gmail.com','ravish@vtu.ac.in','anupama@jssstuniv.in','chitra.hariharan@intel.com','pgp2926@gmail.com','a.pol35@gmail.com','swamyln@gmail.com','sdandagi@gmail.com','veenaschougala@gmail.com','sanjoshi17@yahoo.com','uday.pisute@maximintegrated.com','alok.shukla@getinge.com','ramamurthy_s@hcl.com','raja.manickam@tessolve.com','aliahammed78@gmail.com','ankit.pal@nxp.com','pandralli@gmail.com','prasad.art4life@gmail.com','appinarayan@gmail.com','drhhramesh@gmail.com','ashwin@vtu.ac.in','saangadi@vtu.ac.in','mca.ashwini@gmail.com','sanjay@siliconroad.vc','pavankan04@gmail.com','contactbolnow@gmail.com','michael.seiger@wipro.com','ravindra.hegadal@gmail.com','meghakm@jssstuniv.in','venkatesh.vb@hical.com','yashas.jaiveer@hical.com','rajesh.k@hical.com','sarvesha@starya.in','gowrav@starya.in','arunakar.mishra@genser.com');

	$emails = array('raghunandan@ikpknowledgepark.com','pardeep.s@cleartrip.om','lokesha.n@roi.actcorp.in','shahbuddin.syed@roi.actcorp.in','ramu.m@roi.actcorp.in','naveen.girish@roi.actcorp.in','sp.gmexim@gmail.com','varma@fintel.in','susan.r.thomas@intel.com','sayeedahmed@keys-incorp.com','techconsultant.kbits@gmail.com','catia@aerocoe.in','rameshkumar.p@aerocoe.in','sudarshanprasad.hr@aerocoe.in','badarinarayana.k@aerocoe.in','principal_nmamit@nitte.edu.in','nikhil.dubey@mapit.gov.in','poorvagadre@primuspartners.in','deepak@ideaspringcap.com','karthikrb@gmail.com','upuranik@ykr.co.in','lavanyapg@gmail.com','punitha-cse@saranathan.ac.in','muthamma.kb@tcs.com','vishnampet.sundaram@genessa.co.in','girija.s@esds.co.in','aditya.alok@esds.co.in','neha.n@esds.co.in','avijitgoel@gmail.com','amirh_mirabadi@yahoo.com','drcmanohar@gmail.com','ss@micronel.net','vintinarula@kpmg.com','aparnav@kpmg.com','deepak.singhi@tcs.com','tapan@seniority.in','sainath@amadotools.com','sales@amadotools.com','kr.anjana1@tcs.com','amado@amadotools.com','b2b@lubkarnataka.org','dd.sr@msruas.ac.in','goacontactus@gmail.com','sandeep.aurora@iesaonline.org','mette.svensson@sisp.se','andrew.smith@international.gc.ca','frank.le@international.gc.ca','savitri.patil@refillbot.in','chandra.koduru@tcs.com','george_mohan@outlook.com');

	$emails = array('kavithas@israeltrade.gov.il','mails@srstravels.net','suriya@iesaonline.org','jahnavi.r@neumetric.com','sharada@iesaonline.org','josejacob.k@integro.co.in','shahbhumi63@gmail.com','Meike.Saraswat@invest-in-bavaria.de','priyanka.singh@invest-in-bavaria.in','narottam.sahoo@gmail.com','gmpr@midcindia.org','jtceodmic@midcindia.org','jtceoit@midcindia.org','ceo@midcindia.org','ram@onesource.be','bhojarajcn@lubkarnataka.org','sunil.deshpande@tcs.com','kusuma_k@intuit.com','ravi.teja@cognifirst.com','steinruecke@indo-german.com','nitin.verma@international.gc.ca','rupa.kn@international.gc.ca','neugart@nrwglobalbusiness.com','beeres@nrwglobalbusiness.com','gururajdeshpande@infosys.com','shajim@infosys.com','amar_harish@infosys.com','sales@eri.co.in','alfalabtech@gmail.com','hema@incitecam.com','vijayashribnagavu@gmail.com','Suresh.yadav@botnomics.in','lthomas@globalbusinessinroads.com','ng.subramaniam@tcs.com','shohab.abdullah@semt.gov.in','anjup.bhadoria@mp.gov.in','pdswan@mpsedc.com','md@mpsedc.com','sujsree@iitm.ac.in','pvc.research@msruas.ac.in','shoba.m@tcs.com','srinivasmk@iisc.ac.in','amanjappa@vmware.com','vivektava@gmail.com','prithish.bagchi@gmail.com','rajendrapraveen@gmail.com','rvb@3ds.com','arul@kayadev.com','sanjay.koparde@gokaktextiles.com','SOWMYA@ITEZ.IN');

	$emails = array('JITHINV@ITEZ.IN','shivam@vastra3d.com','anurag@lyso.in','megha_narchal@infosys.com','sowjanya.b@infosys.com','vanita@infosys.com','supprot@eri.co.in','shyam@renalyx.com','shivaprasad@jet.net.in','smeeta_kar@infosys.com','bhargavi.sethuraman@infosys.com','vaishali_tiwari01@infosys.com','swapna_kamath@infosys.com','sunitha_iyer@infosys.com','shreyoshi.das@infosys.com','josepheena_g@infosys.com','priti_sukhavasi@infosys.com','samita_giri@infosys.com','kowsalya_thelakapall@infosys.com','leena_ramachandran@infosys.com','arati.prabhughate@infosys.com','bindu_kalarickal@infosys.com','vienu_leslie@infosys.com','boyina_padmaja@infosys.com','soumyashree.kar@infosys.com','gayatri_panda@infosys.com','shalini_sreeram@infosys.com','sandeepkn.edu@gmail.com','parminder.kakria@wipro.com','subbu@pdsol.in','neha@astrome.co','abecker@nrwglobalbusiness.com','satya@gsasmspl.com','prasad@gecorindia.in','lambaseema14@gmail.com','mohandas@sparrl.com','abhijit.srinivasan@gmail.com','srinivas.j@pixuate.com','digvijay@sensegiz.com','akarsh@shopgro.in','abraham@shopgro.in','shivakumar.kr@indroneaerosys.com','nikhil@kidvento.com','arjun.kashi@ingoelectric.com','sheshavishnuprasad@gmail.com','narasimhan@ken-co.in','arun@janitri.in','abhinavtripathi@22bate7.com','Sevan@nubewell.com','shyam@iotracx.com');

	$emails = array('karthika@skykrafts.com','Akash@scapic.com','varunsesh@gmail.com','saagarikashyamnur@gmail.com','srinivasraju@pisquaretech.com','shilpa@highwaydelite.com','vivek@nasscom.in','aborundiya@nasscom.in','saswat@nasscom.in','shrishu38@gmail.com','jabeen@kepsla.com','jitika@iaccindia.com','nagesh@nasscom.in','rohanym@iGowise.com','klmukesh@scital.com','amar@gnani.ai','siva@gnani.ai','vishwas.odd1@gmail.com','chetanm@havanaa.in','nsupratik@yahoo.com','hareesh@dgtour.in','raghav@xovian.co.in','gettoanjani@gmail.com','contact@myeorder.in','mohitkalra25@gmail.com','rafeq@wincaat.com','janagaran@vdistie.com','naveenjain@myeorder.in','kshitij@mindspaceoutsourcing.com','rnigam@dennemeyer.com','pthakre@dennemeyer.com','kanwal@rdltech.in','ramachandra@rdltech.in','sherin@ka-naada.com','dinesh@varnaaz.com','meeta@worksera.com','yash.voladoddi@gmail.com','chandana.pattanayak@patterneffectslabs.com','shiv.das@patterneffectslabs.com','manjunathhegadesmg@gmail.com','naveen@plugo.io','dawnkhaling@gmail.com','shweta@docketrun.com','vaishalicmath@gmail.com','anusreenp50@gmail.com','pavan.attavane@gmail.com','anaghasonde2108@gmail.com','rajeshthakur@congruenceid.com','cpsuresh3@hotmail.com','divya@dreamsoftin.com');

	$emails = array('ksiddareddy@gmail.com','richardslouis@doifoo.com','ramesh.puttanna@yahoo.in','sharkizhere@gmail.com','ctsatheesh@yahoo.com','vijay@cadence.com','mohit@maapadvisors.in','sharadindia@hotmail.com','prakash.gulati@gmail.com','sampathchari72@gmail.com','somavanshivr@bharatpetroleum.in','pgp09sanjanak@iimrohtak.ac.in','rajiv@yahoo.co.in','rajiv@d1secure.com','kyathsandra.sudharshana@target.com','sindhupriyav05@gmail.com','subbu.swaminathan@gmail.com','radhika.gupta@ap.jll.com','amieth@stownest.com','sudhindra@stownest.com','mailbalajiu@gmail.com','ramakrishna@hotmail.com','vivek.jaiswal@iiml.org','santosh.rk@setplan.in','lakshmichinmoy@gmail.com','chinmoyrajpal@gmail.com','gpbprasanna@gmail.com','rsah9118@gmail.com','suresh@conceptpr.com','kush52662@gmail.com','akshath.shetty@yaralava.com','hbcjaipur@gmail.com','ashokan.amsg@gmail.com','coo@doorpin.zone','sreedhar.aduri@irythu.com','pritam.parashar@gmail.com','gm.sushravya@gmail.com','parakh.aryan93@gmail.com','anandm@ar-ms.in','mr.amitava.sen@gmail.com','yogesh.singh13@gmail.com','trraghavendra@gmail.com','spdongre@gmail.com','kishan.navale@gmail.com','sangeetsindan@gmail.com','sjyotee33@gmail.com','raghavendrakumar@hsbc.co.in','sudipta.mukherjee@sutherlandglobal.com','shaheer.fardan@thefintech.cafe','raj@huawei.com');

	$emails = array('dinesh@quaadbotics.com','brijesh@justrobotics.in','nagoorkani.s@ksrsac.in','A@abc.com','vc@vtu.ac.in','eabalu@eapanacea.com','mgat4@allstate.com','kedar@bionicyantra.com','tgeot@allstate.com','karthikkittu@iiitb.ac.in','rc@iiitb.ac.in','mandappa.coffeeboard@gmail.com','sim.87singh@gmail.com','rudragoudacs@gmail.com','JYOTIP.OJHA@HDFCBANK.COM','director@iiitb.ac.in','Kapil.Singhal@quest-global.com','paindiaoffice2@gmail.com','rubythomasm@gmail.com','sped3.birac@nic.in','ashok.chandavarkar@intel.com','rwimz@allstate.com','sidhartha.mohanty@intel.com','saccp@acu.edu.in','patodirector@karnatakatourism.org','manoj.agarwala@redbus.com','abhl9@allstate.com','rr@syrow.com','Satish.patil@mitibase.com','sri@manipal.net','saurav@tekbrik.com','rimjhim.arora30@gmail.com','sraj6@allstate.com','srinivas.mandyam@allstate.com','dgmsmetcblg@gmail.com','pro@bwssb.gov.in','jneelanjana@ccamp.res.in','centrehead.coe@abai.in','arindum.deb@allstate.com','enquiry@embedsense.com','naavi9@gmail.com','rubytomar.sps@hp.com','enquiry@aspiremediaindia.com','indogermanteam@gmail.com','vinaydora@gmail.com','bankern_20002001@yahoo.co.in','madan@1bridge.one','michael.costa@draft.gov.au','yogesh.kulkarni@interlinks.in','bochen@narlabs.org.tw');

	$emails = array('edyang@narlabs.org.tw','rzwang@narlabs.org.tw','ydkuan@ncut.edu.tw','service@eco-energy.com.tw','atsai0128@gmail.com','yen@eq.ccu.edu.tw','ameena.alshirawi@bahrainedb.com','mohammed.alalawi@bahrainedb.com','farrah.duff@bahrainedb.com','latifa.alkhalifa@bahrainedb.com','bayan.alsayed@bahrainedb.com','mohamed.ashoor@bahrainedb.com','amal.askar@bahrainedb.com','fajer.alpachachi@bahrainedb.com','ameya.rasal@rxpl.in','raman.b@siddsoft.com','anilbhat@myeorder.in','sashank@seconize.co','sarvesh.poddar@sustanix.com','arnoud@nfia-india.com','heine.lageveen@minbuza.nl','joost.geijer@minbuza.nl','anneke.adema@minbuza.nl','m.esser@thehague.com','as@hollandinnovationnetwork.in','ravleen.pal@minbuza.nl','stef.prinsen@innovationquarter.nl','gaurav.verma@dojoko.com','joris.denbruinen@thehaguesecuritydelta.com','a.kiosen@thehague.com','gj@worldstartup.co','gert.heijkoop@minbuza.nl','nde-cdp@minbuza.nl','saskia.bruines@denhaag.nl','arpita@nfia-india.com','bert.feskens@thehaguesecuritydelta.com','ilse-van.dijl@minbuza.nl','vk@hollandinnovationnetwork.in','krishnareddyy7@gmail.com','ruud.vanbroeckhuijsen@denhaag.nl','sujith.vishwanath@minbuza.nl','hemanth.sm@in.bosch.com','swaminathan.k@in.bosch.com','mahesh.medhekar@daimler.com','parthiv.shah@daimler.com','shweta.s.pandey@daimler.com','prasanna.gonuguntla@daimler.com','vyasa.guruprasad@infineon.com','deepak.bachu@infineon.com','aurobind.rath@infineon.com');

	$emails = array('narendra.badve@infineon.com','girish.kamala@infineon.com','mamta.abichandani@infineon.com','ankur@roadzen.io','pallav.chatterjee@in.ey.com','rohan@roadzen.io','nisarg@drivebuddyai.com','vikram.deshpande@siemens.com','chethan.seegehalli@siemens.com','nikhil.mokashi@siemens.com','mr.subramanya@siemens.com','sumit.sharma@indo-german.com','ambika.banotra@gmail.com','mark.beresford@fcdo.gov.uk','sudeshna.ray@fcdo.gov.uk','sijoy.thomas@fcdo.gov.uk','gita.krishnankutty@fcdo.gov.uk','joiston.pereira@fco.gov.uk','shivani.tyagi@fcdo.gov.uk','manjunath.sripathy@fcdo.gov.uk','vikram.joshi@fcdo.gov.uk','rashmi.priyesh@fcdo.gov.uk','fxm@ifindia.in','hemangini.rakshit@diplomatie.gouv.fr','michele.ferrari@diplomatie.gouv.fr','thomas.salez@dgtresor.gouv.fr','daniel.maitre@dgtresor.gouv.fr','sophie.gauthier@diplomatie.gouv.fr','leena.radjibaly@businessfrance.fr','anne.dessemond@businessfrance.fr','eric.fajole@businessfrance.fr','swati.grover@finchamindia.com','aditya.dogra@formin.fi','rai.chakrabarti@formin.fi','richa.sawhney@formin.fi','mikko.potsonen@formin.fi','erik.afhallstrom@formin.fi','nina.jacoby@businessfinland.fi','outi.keski-aijo@businessfinland.fi','teuvo.heikkinen@businessfinland.fi','puneet.thakur@businessfinland.fi','gurpreet.kalsi@businessfinland.fi','dharmesh.sharan@businessfinland.fi','santeri.ojala@businessfinland.fi','jukka.holappa@businessfinland.fi','neeraj.r@hical.com','chairman@aerocoe.in','sudeepa.prakash@esds.co.in','john.kottayil@invest-in-bavaria.in','gmmarketing@midcindia.org');

	$emails = array('venkat@onesource.be','g.raviteja@gmail.com','ajaymalik@mpsedc.com','neelesh@creintors.com','sales@cautomate.com','bhargavi@bhashiniservices.com','vvtavakari@creintors.com','shivam@vastra3d','rahul@lyso.in','navaneetha@openwater.in','shadakshari.swamy@gmail.com','info@pixuate.com','najeebn@tebs.co.in','nagaraj@pixuate.com','deepak.mavinkurve@gmail.com','k@droneaerospace.com','sumanth@kidvento.com','np.aavish@gmail.com','manjunath.panthangi@ingoelectric.com','ashok@wealthstatus.com','keerthi@nubewell.com','RAHUL.SHYAMSHUKHA@MELADATHAUTO.COM','gopi@iotracx.com','sai@scapic.com','rsharma.bgl@gmail.com','sureshs@primerail.com','anarghya.sp@holosuiit.com','neelesh@gnani.ai','harsha@holosuiit.com','manjukg.rao@gmail.com','mayur.d@varnaaz.com','raghu.linkin@gmail.com','hi@viralreplay.com','mgmath@secindia.in','kuwahara.hidemi@sojitz.com','keith@pomelohealth.io','karthik.venkataraman@ul.com','bajay@vmware.com','k.jagadeshwar@gmail.com','jigyasa.luthra@unisys.com','biju@easypay.in','dmalik@fceda.org','');

	$emails = array('hanichethan@gmail.com','monappah64@gmail.com','mamedshareef04402@gmail.com','ravi@makmor.co','acermedia@gmail.com','pesdguy@yahoo.co.in','nikhita928@gmail.com','shivi.jain@ab-inbev.com','vijaydghatta@gmail.com','kapoorrajeme@yahoo.co.in','poojarao123@gmail.com','byra22@gmail.com','shrikant.dole@knorr-bremse.com','venky6171@gmail.com','rk.chugh2010@gmail.com','prashanthullal@gmail.com','anjali.bhola@business-sweden.se','mayurminajgi@gmail.com','nageshr4u@live.in','snaik@gleason.com','prathap.kadam@viscotec-india.com','ashl12.pr@gmail.com','softmanoj@gmail.com','bm.raghavendra@larsentoubro.com','raghu.a.solanki@gmail.com','drsyedshaheeda@gmail.com','reachvijay09@gmail.com','praveena.gowda@gmail.com','supriya@nasscom.in','shobhit1.gupta@intel.com','vijaybalmi@gmail.com','hemant.kumar@stpi.in','prakashgabbur123@gmail.com','sivadas.simatechcnc@gmail.com','samueldayanand@gmail.com','santoshsaraf@git.edu','prashantdhope@gmail.com','malleshkumarks@jnnce.ac.in','achim.burkart@diplo.de','meghnab1@gmail.com','venkikumaran@gmail.com','nilamg.engr@gmail.com','praju22.mu@gmail.com','swamysgs@gmail.com','sandhya.wagh@stpi.in','sheik.sajjad@wpp.com','pankaj.vyas@siemens.com','praju22.mum@gmail.com','bangalore@vdmaindia.org','kaushik@sankaraeye.com','fanny.von.heland@gov.com','drkmanjunatha@gmail.com');

	$emails = array('ola.rignell@saabgroup.com','sumit_malik1@yahoo.com','supriyamurthy64@gmail.com','dean-infrastructure@jnnce.ac.in','nrupatunga@jnnce.ac.in','principal@jnnce.ac.in','supriyamurthy95@gmail.com','khankhurshida28@gmail.com','sraghavendra094@gmail.com','nandishdte@gmail.com','imrangce@gmail.com','naveen022@gmail.com','mdsksjti@gmail.com','vtagore44@gmail.com','amitoj@primuspartners.in','skkustagi66@gmail.com','sreekanthppl@gmail.com','prashanth049@gmail.com','sagarbhovi@gmail.com','megha.mayani@gmail.com');

	$emails = array('satishsvtj@jnnce.ac.in','pracha47@yahoo.com','prathi.gecr@gmail.com','vssgpt@gmail.com','bpallavi178@gmail.com','koushik@ekathvainnovations.com','manjunathprasad07@gmail.com','mskishorekumar@gmail.com','charu@primuspartners.in','mikey@nkdinternational.com');

	$in = 1;
	$mail = new PHPMailer();
	$mail->IsSMTP(); // telling the class to use SMTP
	$mail->SMTPDebug  = 1;                     // enables SMTP debug information (for testing) // 1 = errors and messages // 2 = messages only
	$mail->SMTPAuth   = true;                  // enable SMTP authentication
	$mail->SMTPSecure = "tls";                 // sets the prefix to the servier
	$mail->Host       = "interlinksin.mailserverone.com";      // sets  as the SMTP server
	$mail->Port       = 587;                   // set the SMTP port for the server
	
	if($in == 1) {
		$mail->Username   = "noreply-interlinks";  // username
		$mail->Password   = "NrP#5@lt6ks";            // password	
	} else {
		$mail->Username   = "accounts-interlinks";  // username
		$mail->Password   = "Accounts@123";
	}

	$mail->SetFrom("noreply@interlinks.in", $EVENT_NAME . ' ' . $EVENT_YEAR . ' InterlinX');

	$mail->Subject    = "Thank you for Registration on " . $EVENT_NAME . " " . $EVENT_YEAR . " InterlinX";		
		
	foreach ($emails as $arr) {
		/*print_r($arr);
		echo "<br/>";*/
		$test_delegate_email = $arr;
		$qry_email_chk       = mysqli_query($link,"SELECT * FROM " . $EVENT_DB_FORM_INTERLINX_REG_TBL . " WHERE pri_email = '$test_delegate_email'");
		
		if(mysqli_num_rows($qry_email_chk)) {
			$qr_gt_user_inx_login_data_ans = mysqli_fetch_array($qry_email_chk);

			include "reg_inx_emailer.php";
			//echo $mail_interlinx_str;//exit;

			$str_career_bdy_intx = $mail_interlinx_str;
			$recipients = array($arr);
			//$recipients = array('tejaswini.patil@interlinks.in');
			//$recipients = array('sagar.patil@interlinks.in');
				
			$mail->MsgHTML($str_career_bdy_intx);

			//$recipients = array($qr_gt_user_inx_login_data_ans['pri_email']);
			foreach($recipients as $emailid) {
				$mail->AddAddress($emailid);
				if(!$mail->Send()) {
					echo '<br />#### ' . $emailid . ' ###<br/>';
				} else {
					//echo '<br /><br />##' . $emailid;
				}
				$mail->clearAddresses();
			}//exit;
		}
		//exit;
	}
	echo '<h2> ' . $in . ' You did it well, Teju !</h2>' . $emails[0];
	
?>